version: "3"
services:
  web:
    build:
      context: ../example2
    container_name: mynodeapp
    ports:
      - 8080:80
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
